language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - touch database/database_testing.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --database=sqlite_testing
  - php artisan key:generate

script:
  - vendor/bin/phpunit tests/features
