language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - touch database/database_testing.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --database=sqlite_testing
  - php artisan key:generate

script:
  - mkdir -p build/logs 
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/features

after_script:
  - php vendor/bin/coveralls -v
